name: 'license compliance checker'
description: '⚖️ Scan dependencies for license compatibility'
author: 'rkneela0912'
inputs:
  github_token:
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'check'
  color: 'blue'
